language: cpp
os: linux
addons:
    apt:
        packages:
            - cmake
before_install:
    - mkdir cmake_example
    - cd cmake_example
    - mkdir build
    - cd build
install:
    - cmake ..


