language: cpp
os: linux
addons:
    apt:
        packages:
            - cmake
before_install:
    - cd HelloWorld
    - mkdir build
    - cd build
install:
    - cmake ..
    - make
script:
    - ./main


